REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM anon, authenticated;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO service_role;
GRANT EXECUTE ON FUNCTION public.handle_new_profile() TO service_role;
GRANT EXECUTE ON FUNCTION public.apply_xp_event() TO service_role;
GRANT EXECUTE ON FUNCTION public.ensure_daily_quests() TO service_role;
GRANT EXECUTE ON FUNCTION public.apply_quest_completion() TO service_role;
GRANT EXECUTE ON FUNCTION public.apply_habit_log() TO service_role;
GRANT EXECUTE ON FUNCTION public.enforce_free_tier_journal() TO service_role;
GRANT EXECUTE ON FUNCTION public.prevent_self_billing_change() TO service_role;
GRANT EXECUTE ON FUNCTION public.enforce_xp_event_bounds() TO service_role;
GRANT EXECUTE ON FUNCTION public.enforce_habit_xp_bounds() TO service_role;
GRANT EXECUTE ON FUNCTION public.apply_season_xp() TO service_role;
GRANT EXECUTE ON FUNCTION public.sync_weekly_challenge() TO service_role;
GRANT EXECUTE ON FUNCTION public.ensure_weekly_challenge() TO service_role;
GRANT EXECUTE ON FUNCTION public.build_weekly_reports(date) TO service_role;
GRANT EXECUTE ON FUNCTION public.enforce_free_tier_habits() TO service_role;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, app_role) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.rate_limit_hit(text, integer, integer) TO authenticated, service_role;

GRANT EXECUTE ON FUNCTION public.get_peer_mirror() TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.public_profile_usernames() TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.public_stats() TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.public_profile_ids_by_region(text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.complete_daily_quest(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.public_profile_by_username(text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.create_party(text, text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.join_party_by_code(text) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.award_action_xp(xp_source, uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.check_my_achievements() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.try_consume_notification(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.claim_daily_login_bonus() TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.check_achievements(uuid) TO authenticated, service_role;